### ISSUE TITLE
Frontside : Menu filter issues as no all details are showing

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#665]
If search in menu then in filter result not all info is showing like food type, add to cart, etc.

![image](https://github.com/user-attachments/assets/a33ef37f-4ee8-4906-a790-abbf5eeaeed4)
![image](https://github.com/user-attachments/assets/b087f709-af49-4c1e-bd02-1f84801195a4)

If more search result then UI is not proper
![image](https://github.com/user-attachments/assets/4f6e4148-521d-401a-8923-5307444e3581)

**Comment by rashmipsingh** [comment]
#578 
Resolved in above issue.
Also we applied the JS here, so if UI is not proper then please contact @kaushikpokal for this.

**Comment by patel-nimesh** [comment]
@rashmipsingh Still both issues are arise
Food type is still not showing into food filter
![image](https://github.com/user-attachments/assets/e3aa8c28-d4bb-44bf-b031-aa8fa226cebc)

If designer issue then ask them to fix
![image](https://github.com/user-attachments/assets/e935858a-2a1f-4896-b68d-87fd0d79fd0d)

**Comment by harsh-dhanani** [comment]
@patel-nimesh Its a code structure issue and can be fix by developer

![image](https://github.com/user-attachments/assets/27f60f42-619d-44a8-a2f4-298f07a880a6)

**Comment by rashmipsingh** [comment]
@harsh-dhanani I designed this code structure. Please settle the UI like before it was. I cannot change the code structure.

**Comment by patel-nimesh** [comment]
@rashmipsingh Still the all info not looks proper if more result
![image](https://github.com/user-attachments/assets/277f8418-8357-4db4-820b-aaf8e86a9d69)

**Comment by rashmipsingh** [comment]
![{FFA61228-0843-455C-AD97-3C047E17E54E}](https://github.com/user-attachments/assets/4f2b7ceb-37a6-4cf8-bb65-9328ef55d25f)
@patel-nimesh pls check

**Comment by patel-nimesh** [comment]
Still in my system issue arise
![image](https://github.com/user-attachments/assets/94f97a5a-b344-4319-9793-29fb0a64fc86)

**Comment by rashmipsingh** [comment]
Can you please replicate this issue on stg server? @patel-nimesh

**Comment by patel-nimesh** [comment]
Now this is work properly
![image](https://github.com/user-attachments/assets/735f5238-78bc-4b2b-9213-fa289973d00f)
![image](https://github.com/user-attachments/assets/650b0d1b-7032-4a93-ae61-6694d845433d)
![image](https://github.com/user-attachments/assets/cabcb824-3a68-4dd9-853b-d6054dc6004e)
![image](https://github.com/user-attachments/assets/85153a5d-aa4b-4d66-88c9-d82e1c86c567)
